name: Epic
description: Create a Epic
title: "[Epic:] "
labels: ["epic"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this epic!

  - type: textarea
    attributes:
      label: Epic Description
      description: Why is this epic needed?
      placeholder: Why is this epic needed?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem to be Solved
      description: What problem would be solved?
      placeholder: What problem would be solved?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: What is the solution this epic will solve?
      placeholder: What is the solution this epic will solve?
    validations:
      required: true

  - type: input
    attributes:
      label: Related Stories
      description: All related stories
      placeholder: i.e 7, 8

  - type: input
    attributes:
      label: Related Tasks
      description: All related tasks
      placeholder: i.e 4, 5

  - type: textarea
    attributes:
      label: Business Outcome
      description: What is the business outcome?
      placeholder: What is the business outcome?

  - type: checkboxes
    id: severity
    attributes:
      label: Severity
      options:
        - label: Major
        - label: Minor
        - label: Trival
          required: true
  
  - type: input
    attributes:
      label: Time to Complete
      description: How long will it take to complete?
      placeholder: How long will it take to complete?
