name: Story
description: Create a Story
title: "[Story:] "
labels: ["story"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this story!

  - type: input
    attributes:
      label: User Type
      description: What type of user is this story for
      placeholder: As a [insert type of user]
    validations:
      required: true

  - type: input
    attributes:
      label: User wants
      description: What does the user want/need
      placeholder: I want [insert what the user wants]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why the user has this want
      description: Describe what the user wants
      placeholder: Because [insert why the user wants/needs this feature]
    validations:
      required: true

  - type: input
    attributes:
      label: Related Epics
      description: All related epics
      placeholder: i.e 7, 8

  - type: input
    attributes:
      label: Related Tasks
      description: All related tasks
      placeholder: i.e 4, 5

  - type: checkboxes
    id: severity
    attributes:
      label: Severity
      options:
        - label: Major
        - label: Minor
        - label: Trival
          required: true
  
  - type: input
    attributes:
      label: Time to Complete
      description: How long will it take to complete?
      placeholder: How long will it take to complete?