name: Task
description: Create a task for someone to do
title: "[Task:] "
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this task!

  - type: textarea
    attributes:
      label: Task Description 
      description: Tells the reader what to do
      placeholder: What needs to be done? Add images if needed
    validations:
      required: true

  - type: input
    attributes:
      label: Related Stories
      description: All related stories
      placeholder: i.e 7, 8

  - type: input
    attributes:
      label: Related Epics
      description: All related epics
      placeholder: i.e 4, 5

  - type: checkboxes
    id: severity
    attributes:
      label: Severity
      options:
        - label: Major
        - label: Minor
        - label: Trival
          required: true

  - type: input
    attributes:
      label: Time to Complete
      description: How long will it take to complete?
      placeholder: How long will it take to complete?